### ISSUE TITLE
Require an aggregator

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/hobbes-network-format#1]
A common problem is that we need to summarize a number of network nodes or links.  I propose that in the hnf, we create a generic aggregation, somewhat in the spirit of postgres.  The function gets passed a list of nodes/links, a summation function, initial object, a finalize function and a callback. The routine serially runs the summation function on each item, then the finalizer, then the callback.  Also, the routine will expand the links if required.   Therefore we can only expand the data we need, and not use the crawler for that.

``` js
var list=[ list_of_features];

var sum=function(item,agg) {
  var net = item.properties;
  var inflow={};
   if (net.inflows) {
      for (var key in net.inflows) {
         var csv=net.inflows[key].inflow;
         csv.forEach(function(d) {
            inflow[d[0]]+=d[1];});
         }
   }
   agg[net.prmname]=inflow
};

var final=function(agg) { return agg; } 

hnf.aggregation(list,{inflows=[]},sum,final,function(agg) {
console.log(agg);});
```

**Comment by jrmerz** [comment]
Sounds mapreduce-ish.  Since this functionality is easily added by any project requiring the hnf module, I'm assuming you only mean for command line interface?  Something like --aggregator myAgg.js, program would expect the following interface:

``` javascript
module.exports = {
  init : function(base) {

  },
  aggregate : function(item, base, next) {

  },
  finalize : function(base) {

  }
}
```

though we could simplify to:

``` javascript
var base = {};
module.exports = {
  aggregate : function(item, next) {

  },
  finalize : function() {

  }
}
```

**Comment by qjhart** [comment]
@jrmerz, I didn't complete my thoughts, but you have the idea.  Regarding your ideas above, I like that.  The bottom one might be slightly different (and more mapreduceish) if you had no next even, you just updated the base, and worked in some order.

However, I have to say that I did not find it easy to write this, primarily because of desire to be lazy in the csv file reading, and not in the crawler. It's quite possible that I missed this part of the HNF tools.  This is maybe off topic but it it worthwhile to have a promise for that?  Do we use promises? 

``` js
hnf.expand(node,['inflows','evaporation']).then(function(node) {
 // do something cool.
}).catch(function(err{});
# or though I don't think you like this stye.
node.expand(['inflows','evaporation']).then(....);
```

**Comment by jrmerz** [comment]
Couple notes.
- The **next** callback is required in case you have any async operations (which most operations in node are) inside the aggregate function.  This is exactly how the async module works, and what will more than likely control the calling of the aggregate function.
- The hnf module does not currently have a lazy loader for csv data.  I can add one.  We will need to pass a reference to the hnf library into 'myAgg' in this case.  Easy to do.
- We CAN use promises here.  I do not use any (most) ES6 functionality in most of my code as many libraries need to run in the browser and I don't want to add babel to the build process.  This is not the case for this library, so I would say promises are free game if you want.

**Comment by qjhart** [comment]
Yeah, I was just saying that map-reduce has no order in their mapping, and so they have no next.  It's a minor thing.

To be clear, is one of the items below the pattern I would use in a module?

``` js
crawler(config.data, {parseCsvData : false}, function(results){
  var node, i;
  var list = [];
      for( i = 0; i < results.nodes.features.length; i++ ) {
        node = results.nodes.features[i];
        if(nodes.indexOf(node.properties.prmname.toUpperCase()) > -1 ) {
          list.push(node);
        }
    }
```

Then, either

``` js
  async.eachSeries(list,
    function(node,next) {
      hnf.expand(node,['inflows']).then(function(node) {
         //do something}).catch();
   });
```

Or expanding a set of nodes at one go?

``` js
hnf.expand(list,['inflows']).then(function(list) {
  list.forEach(function() { //do something })
 .catch(function(err0{});
```

**Comment by jrmerz** [comment]
The **next** function is not about order, it's about asynchronous action.  And there is no reason our control flow will guarantee order either, in fact we can run async parallel behind the scenes.

Your examples above looks like you want a js snippet where the initialized **hnf** is passed into the module?  Then you call expand from there?

**Comment by qjhart** [comment]
I beg to differ, [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), but that's not too important.

Yes, expand called in script.  Regarding the method passing, yes you are correct.  In fact, that I can imagine having a crawler free implementation as in: 

``` js
var dir=~/foo;
var hnf=require('hnf',dir);
// or hnf.connect(dir)
var list=hnf.network({expand=false});
// Then as above.
```

A db vs. filesystem could be abstracted away, but I don't want to presume that interface too much.
That was one reason for addind id's to the geojson file, you could return much faster. with non expanded ids

**Comment by jrmerz** [comment]
Not sure why you differ, async operations are a fundamental part of NodeJS.  Creating an aggregator that that does not let you use any async method inside seems like your are greatly reducing the functionality.  And I can post docs too :) [async](https://github.com/caolan/async/blob/master/README.md)

But that actually gets to a bigger point.  I thought you wanted to use the command line and supply a simple script to do some work w/o creating a new project, importing modules from npm, etc, etc.  But now it looks like you just want a helper for looping over the array that is supplied by the result of the default crawl functionality.  Not sure I understand the utility in that.  The snippet you gave in the last post is how this module currently works...

``` js
var crawler = require('hobbes-network-format');
var dir = '/Users/jrmerz/foo';

// expand === parseCsvData
crawler(dir, {parseCsvData: true}, function(resp){
  crawlerResponse.nodes.features.forEach(feature => {
   // do stuff
  });

  crawlerResponse.regions.features.forEach(feature => {
   // do stuff
  });
});
```

So what functionality are you wanting to add?  Just the individual expand helper method?  So code would look like:

``` js
var hnf = require('hobbes-network-format');
var async = require('async');
var dir = '/Users/jrmerz/foo';

hnf.crawl(dir, {parseCsvData: false}, function(resp){
  async.eachSeries(
    crawlerResponse.nodes.features,
    function(feature, next) {
      hnf.expand(feature, ['inflows'], function(feature) {
         next();
      });
    },
    function(err) {
      // finalize
    }
  );

});
```

**Comment by qjhart** [comment]
Moving the expand discussion to #2.  No, I like the notion of aggregation modules: 

``` js
module.exports = {
  init : function(base) { },
  expand:['inflows','evaporation']
  aggregate : function(item, base, next) {  },
  finalize : function(base) {  }
}
```

As a general tool.  I also like it if you can capture most errors that are not related to the aggregation, but also let these functions return errors as well, but also get captured by the aggregator.  So for example if the aggregate has a divide by 0, it returns an error, and the aggregator stops.  

Note, it seems like we need to give some hints to the expander above, I think.

However, since 95% of our aggregators will be built into a command, I'd like to see what that template looks like.  Is it something like this? 

``` js
var hnf = require('hobbes-network-format');
var my_agg = require('./my_agg');
var dir = '/Users/jrmerz/foo';
var list= [];
hnf.crawl(dir, {parseCsvData: false}, function(resp){
  if (filter to some subset of nodes, as in passed on command line) {
    list.push(resp);
  }},
 function(err) { console.log('Bad DB'+dir);} );

hnf.aggregate(list,my_agg,function(aggregate) {
  // Process Aggregate
},
function(err) { console.log('Error:'+err)});
```
